# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c13e4acb29b36e8b609abcf5fd5f6387ddfeeb794012debba3210ac7b938cd02ac12da1048ea0b69af48ee6d0e187435545ebff5098a169c017118455f8a612

test:
  secret_key_base: 54b8da65e3ab4db0d1c71e78b648f932c184d13bc4a6dd54e19eafc75c7599ee7ddf09e2d8a5dd34f5aa3f67f4b9138633141fb39632ce16ff7c9392870c18f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
